name: secure_storage
description: A Key-Value Secure Storage Client
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  storage:
    path: ../storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^6.0.0

dependency_overrides:
  # temporary fix for https://github.com/mogol/flutter_secure_storage/issues/709
  flutter_secure_storage: 9.0.0
  flutter_secure_storage_linux: 1.2.0
  flutter_secure_storage_macos: 3.0.1
  flutter_secure_storage_platform_interface: 1.0.2
  flutter_secure_storage_web: 1.2.0
  flutter_secure_storage_windows: 3.0.0
